// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqB_iFttUx7pfI6t1RYcj-AeWXA-srUrw',
    appId: '1:536639021521:web:50da3a1b50f89f331ec0f0',
    messagingSenderId: '536639021521',
    projectId: 'monkey-messanger',
    authDomain: 'monkey-messanger.firebaseapp.com',
    storageBucket: 'monkey-messanger.firebasestorage.app',
    measurementId: 'G-KM9VREXJQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKEm7akmIqkf9Dc7EWdSyZ2f0mRyhPf-E',
    appId: '1:536639021521:android:78a034d791badc141ec0f0',
    messagingSenderId: '536639021521',
    projectId: 'monkey-messanger',
    storageBucket: 'monkey-messanger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEPU2dcB2QoBk1V1Hd7NPf-LFWRnUmQGg',
    appId: '1:536639021521:ios:7d0e6428c2e4eac71ec0f0',
    messagingSenderId: '536639021521',
    projectId: 'monkey-messanger',
    storageBucket: 'monkey-messanger.firebasestorage.app',
    iosBundleId: 'com.example.monkeyMessanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEPU2dcB2QoBk1V1Hd7NPf-LFWRnUmQGg',
    appId: '1:536639021521:ios:7d0e6428c2e4eac71ec0f0',
    messagingSenderId: '536639021521',
    projectId: 'monkey-messanger',
    storageBucket: 'monkey-messanger.firebasestorage.app',
    iosBundleId: 'com.example.monkeyMessanger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqB_iFttUx7pfI6t1RYcj-AeWXA-srUrw',
    appId: '1:536639021521:web:1971142d967aa0de1ec0f0',
    messagingSenderId: '536639021521',
    projectId: 'monkey-messanger',
    authDomain: 'monkey-messanger.firebaseapp.com',
    storageBucket: 'monkey-messanger.firebasestorage.app',
    measurementId: 'G-DFKM3KL6HD',
  );
}
